'use client'

import { Inter } from "next/font/google";

import Footer from '/src/app/components/Footer'
import Header from '/src/app/components/Header'

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={`overfolw-x-hidden  ${inter.className}`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
